#define INPUT_PIN1_PIXELS_MODE 3
#define INPUT_PIN2_PIXELS_MODE 4

#define OUTPUT_PIN_NEOPIXELS_TAIL 6
#define OUTPUT_PIN_NEOPIXELS_FRONT_CENTER 7

#define OUTPUT_PIN_NEOPIXELS_FRONT_LEFT 9
#define OUTPUT_PIN_NEOPIXELS_FRONT_RIGHT 12
#define OUTPUT_PIN_NEOPIXELS_REAR_LEFT 10
#define OUTPUT_PIN_NEOPIXELS_REAR_RIGHT 11
